spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/outsourcing
    password: '12345678'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
  application:
    name: outsourcing-projects
jwt:
  secret:
    key: